### ISSUE TITLE
Windows CLI .exe Warning

### ISSUE THREAD

**Issue by naetraga** [corbado/cli#3]
Bei Doppelklick auf die CLI kommt folgende Warning:

![Image](https://user-images.githubusercontent.com/18458907/220965535-0720e570-89dd-4c0d-999b-fbca835b007a.png)

Können wir das signieren bzw. umstellen, dass die Warnung nicht mehr kommt?
Prinzipiell funktioniert alles, wenn man nicht auf die .exe per Doppelklickt klickt

**Comment by naetraga** [comment]
wir brauchen hierzu ein code signing zertifikat. die sind alle kostenpflichtig. @vincentdelitz bitte in der doku vermerken.

**Comment by vincentdelitz** [comment]
hab einen Vermerk in der Doku geaddet
